### Cadastrar usuário
POST http://localhost:8080/usuarios
Content-Type: application/json

{
  "nome": "Misael Dutra",
  "email": "misael@gmail.com",
  "senha": "123599"
}


### Listar usuários
GET http://localhost:8080/usuarios

### Buscar usuário por ID
GET http://localhost:8080/usuarios/1

### Buscar usuário inexistente
GET http://localhost:8080/usuarios/999

### Atualizar usuário
PUT http://localhost:8080/usuarios/1
Content-Type: application/json


{
  "nome": "Jonatas",
  "email": "jonatasnovo@email.com",
  "senha": "4321"
}

### Deletar usuário
DELETE http://localhost:8080/usuarios/1

### Teste validação
POST http://localhost:8080/usuarios
Content-Type: application/json

{
  "nome": "",
  "email": "misael",
  "senha": ""
}

### Teste email duplicado
POST http://localhost:8080/usuarios
Content-Type: application/json

{
  "nome": "Carlos",
  "email": "misael@gmail.com",
  "senha": "123456"
}