### Cadastrar usuário
POST http://localhost:8080/usuarios
Content-Type: application/json

{
  "nome": "Misael Dutra",
  "email": "misael@gmail.com",
  "senha": "1235"
}


### Listar usuários
GET http://localhost:8080/usuarios

### Buscar usuário por ID
GET http://localhost:8080/usuarios/33

### Atualizar usuário
PUT http://localhost:8080/usuarios/1
Content-Type: application/json

{
  "nome": "Jonatas",
  "email": "jonatasnovo@email.com",
  "senha": "4321"
}


### Deletar usuário
DELETE http://localhost:8080/usuarios/1